version: '3.4'
services:
   database:
      image: "postgres" # use latest official postgres version
      container_name: ${DB_NAME}
      ports:
         - ${DB_PORT}:5432
      environment:
         POSTGRES_USER: ${DB_USER} 
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_NAME}
         POSTGRES_HOST: localhost
      volumes:
         - data:/var/lib/postgresql/data/ # persist data even if container shuts down
         - postgres.conf:/usr/local/etc/postgres/postgres.conf
         - pg_hba.conf:/var/lib/data/pg_hba.conf
      network_mode: bridge
volumes:
   data:
   postgres.conf:
   pg_hba.conf:

